apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: u5yme5og4-java-springboot
  janus-idp.io/tekton: u5yme5og4-java-springboot
  backstage.io/kubernetes-id: u5yme5og4-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u5yme5og4-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
